// src/components/ui/input.tsx
"use client"
import * as React from "react";
import { cn } from "@/lib/utils";
import Image from "next/image";

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> { }

const Input = React.forwardRef<HTMLInputElement, InputProps>(({ className, type = "text", id, placeholder, ...props }, ref) => {
  const [visiblePassword, setVisiblePassword] = React.useState(false)
  function handleVisiblePassword(e: React.MouseEvent<HTMLButtonElement>) {
    e.preventDefault()
    setVisiblePassword(state => !state)
  }

  return (
    <div className="relative">
      <input
        id={id}
        type={type !== "password" ? type : visiblePassword ? "text" : "password"}
        className={cn(
          "peer placeholder-transparent flex h-12 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-app focus-visible:ring-offset-1 disabled:cursor-not-allowed disabled:opacity-50",
          className
        )}
        ref={ref}
        placeholder={placeholder}
        {...props}
      />
      <label
        htmlFor={id}
        className="absolute -top-6 left-3 text-sm text-slate-800 peer-focus:text-primary-app peer-focus:-top-6 peer-placeholder-shown:top-4 peer-placeholder-shown:text-gray-400 duration-200"
      >
        {placeholder}
      </label>
      {
        type === "password" &&
        <button className="absolute right-3 top-4" onClick={(e) => handleVisiblePassword(e)}>
          {
            visiblePassword ?
              <Image src={"/icons/invisible-password.svg"} alt="Invisible password icon" height={18} width={18} />
              :
              <Image src={"/icons/visible-password.svg"} alt="Visible password icon" height={18} width={18} />
          }
        </button>
      }
    </div>
  );
}
);
Input.displayName = "Input";

export default Input;

// components/ui/input/Input.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'
import { useVModel } from '@vueuse/core'

const props = defineProps<{
  defaultValue?: string | number
  modelValue?: string | number
  class?: HTMLAttributes['class']
}>()

const emits = defineEmits<{
  (e: 'update:modelValue', payload: string | number): void
}>()

const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue: props.defaultValue,
})
</script>

<template>
  <input
    v-model="modelValue"
    data-slot="input"
    :class="cn(
      'file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
      'focus-visible:border-primary focus-visible:ring-ring/50 focus-visible:ring-[3px]',
      'aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive',
      props.class,
    )"
  >
</template>
