// components/provider/AlertProvider.vue
<script setup lang="ts">
import { useAlertStore } from "~/store/useAlertStore";
import { Alert, AlertDescription, AlertTitle, type AlertVariants } from "../ui/alert";

const alert = useAlertStore();
const alertStyle = computed(() => {
  return alert.isShow ? "translate-x-0 right-4" : "translate-x-full";
});

watchEffect(() => {
  if (alert.isShow) {
    setTimeout(() => {
      alert.hideAlert();
    }, 10000);
  }
});
</script>

<template>
    <Alert
      :variant="alert.variant"
      :class="[
        'fixed top-2 right-0 transition-transform duration-300 ease-in-out z-50',
        alertStyle,
      ]"
    >
      <AlertTitle>{{ alert.title }}</AlertTitle>
      <AlertDescription>{{ alert.description }}</AlertDescription>
  </Alert>
</template>

// src/components/provider/AlertProvider.tsx
"use client"
import React, { useEffect } from 'react'
import { Alert, AlertDescription, AlertTitle } from '../ui/alert'
import { AlertStore } from '@/store/alertStore'
import { useShallow } from 'zustand/react/shallow'

export default function AlertProvider() {
    const { alert, setAlert } = AlertStore(useShallow((state) => ({ alert: state.alert, setAlert: state.setAlert })))
    const { isShowAlert, alertTitle, alertDescription } = alert
    
    useEffect(() => {
        if(isShowAlert) {
            setTimeout(() => {
                setAlert({...alert, isShowAlert: false})
            }, 3000)
        }
    }, [isShowAlert, alert, setAlert])

    return (
        <>
            <Alert className={`w-fit h-max fixed top-3 z-[9999] duration-500 ${isShowAlert ? "right-6 visible opacity-100" : "-right-full invisible opacity-0"}`}>
                <AlertTitle>
                    {alertTitle}
                </AlertTitle>
                <AlertDescription>
                    {alertDescription}
                </AlertDescription>
            </Alert>

        </>
    )
}
