// src/components/element/recipe_list/EmptyRecipeList.tsx
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

export default function EmptyRecipeList() {
    return (
        <section className='w-full h-full flex flex-col justify-center items-center gap-y-5'>
            <Image src={"/icons/empty-recipe.svg"} alt="empty recipe" height={2160} width={3840} className='w-32 aspect-auto' />
            <h1 className="text-3xl">No recipes yet</h1>
            <p className='font-light'>Feeling hungry? <Link className='text-primary-app underline underline-offset-2' href={"/"}>Browse recipe!</Link></p>
        </section>
    )
}

// components/elements/recipe/EmptyRecipeList.vue
<script lang="ts" setup></script>

<template>
  <div class="min-h-4/5 w-full flex flex-col justify-center items-center">
    <img class="h-60" src="/image/empty-recipe.png" />
    <div class="text-center">
      <h1 class="text-2xl">Resep Kosong!</h1>
      <span class="text-sm">
        <NuxtLink href="/new-recipe" class="text-primary hover:text-primary/75"
          >Buat Resep</NuxtLink
        >
        atau
        <NuxtLink href="/" class="text-primary hover:text-primary/75"
          >Cari Resep</NuxtLink
        >
      </span>
    </div>
  </div>
</template>
